version: "3.9"

services:
  mysql:
    image: mysql:latest
    env_file: "sql_env.env"
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped

  app:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      - HOST=mysql
      - PORT=3306

volumes:
  mysql-data:
    driver: local
